services:
  - type: web
    name: fpi-sx-bot
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: "@XcT_x_HostinG_BoT"
      - key: OWNER_ID
        sync: false
      - key: OWNER_USERNAME
        value: "XcT_xAyOuB"
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
